#!/bin/bash

PROG=$@

if [ $# == 0 ]; then
    echo "Usage"
    echo "$0 <command line>"
    exit
fi

#PINHOME=/home/xdzhang/work/dytan/pin-3.0
PINHOME=/home/lihao/dytan_pct/pin-2.14-71313-gcc.4.4.7-linux
DYTAN=/home/lihao/dytan_pct/obj-intel64
$PINHOME/intel64/bin/pinbin -t $DYTAN/dytan -injection child -- $PROG
